export default {
  queryType: { name: 'query_root' },
  mutationType: { name: 'mutation_root' },
  subscriptionType: { name: 'subscription_root' },
  types: [
    {
      kind: 'SCALAR',
      name: 'Boolean',
      description: null,
      fields: null,
      inputFields: null,
      interfaces: null,
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'SCALAR',
      name: 'Float',
      description: null,
      fields: null,
      inputFields: null,
      interfaces: null,
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'SCALAR',
      name: 'Int',
      description: null,
      fields: null,
      inputFields: null,
      interfaces: null,
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'SCALAR',
      name: 'String',
      description: null,
      fields: null,
      inputFields: null,
      interfaces: null,
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'OBJECT',
      name: '__Directive',
      description: null,
      fields: [
        {
          name: 'args',
          description: null,
          args: [],
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'LIST',
              name: null,
              ofType: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'OBJECT',
                  name: '__InputValue',
                  ofType: null,
                  __typename: '__Type',
                },
                __typename: '__Type',
              },
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'description',
          description: null,
          args: [],
          type: {
            kind: 'SCALAR',
            name: 'String',
            ofType: null,
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'locations',
          description: null,
          args: [],
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'LIST',
              name: null,
              ofType: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'ENUM',
                  name: '__DirectiveLocation',
                  ofType: null,
                  __typename: '__Type',
                },
                __typename: '__Type',
              },
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'name',
          description: null,
          args: [],
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'SCALAR',
              name: 'String',
              ofType: null,
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
      ],
      inputFields: null,
      interfaces: [],
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'ENUM',
      name: '__DirectiveLocation',
      description: null,
      fields: null,
      inputFields: null,
      interfaces: null,
      enumValues: [
        {
          name: 'ARGUMENT_DEFINITION',
          description: null,
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'ENUM',
          description: null,
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'ENUM_VALUE',
          description: null,
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'FIELD',
          description: null,
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'FIELD_DEFINITION',
          description: null,
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'FRAGMENT_DEFINITION',
          description: null,
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'FRAGMENT_SPREAD',
          description: null,
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'INLINE_FRAGMENT',
          description: null,
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'INPUT_FIELD_DEFINITION',
          description: null,
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'INPUT_OBJECT',
          description: null,
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'INTERFACE',
          description: null,
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'MUTATION',
          description: null,
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'OBJECT',
          description: null,
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'QUERY',
          description: null,
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'SCALAR',
          description: null,
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'SCHEMA',
          description: null,
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'SUBSCRIPTION',
          description: null,
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'UNION',
          description: null,
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
      ],
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'OBJECT',
      name: '__EnumValue',
      description: null,
      fields: [
        {
          name: 'deprecationReason',
          description: null,
          args: [],
          type: {
            kind: 'SCALAR',
            name: 'String',
            ofType: null,
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'description',
          description: null,
          args: [],
          type: {
            kind: 'SCALAR',
            name: 'String',
            ofType: null,
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'isDeprecated',
          description: null,
          args: [],
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'SCALAR',
              name: 'Boolean',
              ofType: null,
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'name',
          description: null,
          args: [],
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'SCALAR',
              name: 'String',
              ofType: null,
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
      ],
      inputFields: null,
      interfaces: [],
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'OBJECT',
      name: '__Field',
      description: null,
      fields: [
        {
          name: 'args',
          description: null,
          args: [],
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'LIST',
              name: null,
              ofType: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'OBJECT',
                  name: '__InputValue',
                  ofType: null,
                  __typename: '__Type',
                },
                __typename: '__Type',
              },
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'deprecationReason',
          description: null,
          args: [],
          type: {
            kind: 'SCALAR',
            name: 'String',
            ofType: null,
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'description',
          description: null,
          args: [],
          type: {
            kind: 'SCALAR',
            name: 'String',
            ofType: null,
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'isDeprecated',
          description: null,
          args: [],
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'SCALAR',
              name: 'Boolean',
              ofType: null,
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'name',
          description: null,
          args: [],
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'SCALAR',
              name: 'String',
              ofType: null,
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'type',
          description: null,
          args: [],
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'OBJECT',
              name: '__Type',
              ofType: null,
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
      ],
      inputFields: null,
      interfaces: [],
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'OBJECT',
      name: '__InputValue',
      description: null,
      fields: [
        {
          name: 'defaultValue',
          description: null,
          args: [],
          type: {
            kind: 'SCALAR',
            name: 'String',
            ofType: null,
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'description',
          description: null,
          args: [],
          type: {
            kind: 'SCALAR',
            name: 'String',
            ofType: null,
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'name',
          description: null,
          args: [],
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'SCALAR',
              name: 'String',
              ofType: null,
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'type',
          description: null,
          args: [],
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'OBJECT',
              name: '__Type',
              ofType: null,
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
      ],
      inputFields: null,
      interfaces: [],
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'OBJECT',
      name: '__Schema',
      description: null,
      fields: [
        {
          name: 'directives',
          description: null,
          args: [],
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'LIST',
              name: null,
              ofType: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'OBJECT',
                  name: '__Directive',
                  ofType: null,
                  __typename: '__Type',
                },
                __typename: '__Type',
              },
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'mutationType',
          description: null,
          args: [],
          type: {
            kind: 'OBJECT',
            name: '__Type',
            ofType: null,
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'queryType',
          description: null,
          args: [],
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'OBJECT',
              name: '__Type',
              ofType: null,
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'subscriptionType',
          description: null,
          args: [],
          type: {
            kind: 'OBJECT',
            name: '__Type',
            ofType: null,
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'types',
          description: null,
          args: [],
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'LIST',
              name: null,
              ofType: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'OBJECT',
                  name: '__Type',
                  ofType: null,
                  __typename: '__Type',
                },
                __typename: '__Type',
              },
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
      ],
      inputFields: null,
      interfaces: [],
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'OBJECT',
      name: '__Type',
      description: null,
      fields: [
        {
          name: 'description',
          description: null,
          args: [],
          type: {
            kind: 'SCALAR',
            name: 'String',
            ofType: null,
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'enumValues',
          description: null,
          args: [
            {
              name: 'includeDeprecated',
              description: null,
              type: {
                kind: 'SCALAR',
                name: 'Boolean',
                ofType: null,
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
          ],
          type: {
            kind: 'LIST',
            name: null,
            ofType: {
              kind: 'NON_NULL',
              name: null,
              ofType: {
                kind: 'OBJECT',
                name: '__EnumValue',
                ofType: null,
                __typename: '__Type',
              },
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'fields',
          description: null,
          args: [
            {
              name: 'includeDeprecated',
              description: null,
              type: {
                kind: 'SCALAR',
                name: 'Boolean',
                ofType: null,
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
          ],
          type: {
            kind: 'LIST',
            name: null,
            ofType: {
              kind: 'NON_NULL',
              name: null,
              ofType: {
                kind: 'OBJECT',
                name: '__Field',
                ofType: null,
                __typename: '__Type',
              },
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'inputFields',
          description: null,
          args: [],
          type: {
            kind: 'LIST',
            name: null,
            ofType: {
              kind: 'NON_NULL',
              name: null,
              ofType: {
                kind: 'OBJECT',
                name: '__InputValue',
                ofType: null,
                __typename: '__Type',
              },
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'interfaces',
          description: null,
          args: [],
          type: {
            kind: 'LIST',
            name: null,
            ofType: {
              kind: 'NON_NULL',
              name: null,
              ofType: {
                kind: 'OBJECT',
                name: '__Type',
                ofType: null,
                __typename: '__Type',
              },
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'kind',
          description: null,
          args: [],
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'ENUM',
              name: '__TypeKind',
              ofType: null,
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'name',
          description: null,
          args: [],
          type: {
            kind: 'SCALAR',
            name: 'String',
            ofType: null,
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'ofType',
          description: null,
          args: [],
          type: {
            kind: 'OBJECT',
            name: '__Type',
            ofType: null,
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'possibleTypes',
          description: null,
          args: [],
          type: {
            kind: 'LIST',
            name: null,
            ofType: {
              kind: 'NON_NULL',
              name: null,
              ofType: {
                kind: 'OBJECT',
                name: '__Type',
                ofType: null,
                __typename: '__Type',
              },
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
      ],
      inputFields: null,
      interfaces: [],
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'ENUM',
      name: '__TypeKind',
      description: null,
      fields: null,
      inputFields: null,
      interfaces: null,
      enumValues: [
        {
          name: 'ENUM',
          description: null,
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'INPUT_OBJECT',
          description: null,
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'INTERFACE',
          description: null,
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'LIST',
          description: null,
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'NON_NULL',
          description: null,
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'OBJECT',
          description: null,
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'SCALAR',
          description: null,
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'UNION',
          description: null,
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
      ],
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'ENUM',
      name: 'conflict_action',
      description: 'conflict action',
      fields: null,
      inputFields: null,
      interfaces: null,
      enumValues: [
        {
          name: 'ignore',
          description: 'ignore the insert on this row',
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'update',
          description: 'update the row with the given values',
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
      ],
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'INPUT_OBJECT',
      name: 'integer_comparison_exp',
      description:
        "expression to compare columns of type integer. All fields are combined with logical 'AND'.",
      fields: null,
      inputFields: [
        {
          name: '_eq',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'Int',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: '_gt',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'Int',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: '_gte',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'Int',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: '_in',
          description: null,
          type: {
            kind: 'LIST',
            name: null,
            ofType: {
              kind: 'SCALAR',
              name: 'Int',
              ofType: null,
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: '_is_null',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'Boolean',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: '_lt',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'Int',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: '_lte',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'Int',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: '_neq',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'Int',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: '_nin',
          description: null,
          type: {
            kind: 'LIST',
            name: null,
            ofType: {
              kind: 'SCALAR',
              name: 'Int',
              ofType: null,
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
      ],
      interfaces: null,
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'OBJECT',
      name: 'mutation_root',
      description: 'mutation root',
      fields: [
        {
          name: 'delete_post',
          description: 'delete data from the table: "post"',
          args: [
            {
              name: 'where',
              description: 'filter the rows which have to be deleted',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'INPUT_OBJECT',
                  name: 'post_bool_exp',
                  ofType: null,
                  __typename: '__Type',
                },
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
          ],
          type: {
            kind: 'OBJECT',
            name: 'post_mutation_response',
            ofType: null,
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'delete_user',
          description: 'delete data from the table: "user"',
          args: [
            {
              name: 'where',
              description: 'filter the rows which have to be deleted',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'INPUT_OBJECT',
                  name: 'user_bool_exp',
                  ofType: null,
                  __typename: '__Type',
                },
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
          ],
          type: {
            kind: 'OBJECT',
            name: 'user_mutation_response',
            ofType: null,
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'insert_post',
          description: 'insert data into the table: "post"',
          args: [
            {
              name: 'objects',
              description: 'the rows to be inserted',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'LIST',
                  name: null,
                  ofType: {
                    kind: 'NON_NULL',
                    name: null,
                    ofType: {
                      kind: 'INPUT_OBJECT',
                      name: 'post_insert_input',
                      ofType: null,
                      __typename: '__Type',
                    },
                    __typename: '__Type',
                  },
                  __typename: '__Type',
                },
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
            {
              name: 'on_conflict',
              description: 'on conflict condition',
              type: {
                kind: 'INPUT_OBJECT',
                name: 'post_on_conflict',
                ofType: null,
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
          ],
          type: {
            kind: 'OBJECT',
            name: 'post_mutation_response',
            ofType: null,
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'insert_user',
          description: 'insert data into the table: "user"',
          args: [
            {
              name: 'objects',
              description: 'the rows to be inserted',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'LIST',
                  name: null,
                  ofType: {
                    kind: 'NON_NULL',
                    name: null,
                    ofType: {
                      kind: 'INPUT_OBJECT',
                      name: 'user_insert_input',
                      ofType: null,
                      __typename: '__Type',
                    },
                    __typename: '__Type',
                  },
                  __typename: '__Type',
                },
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
            {
              name: 'on_conflict',
              description: 'on conflict condition',
              type: {
                kind: 'INPUT_OBJECT',
                name: 'user_on_conflict',
                ofType: null,
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
          ],
          type: {
            kind: 'OBJECT',
            name: 'user_mutation_response',
            ofType: null,
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'update_post',
          description: 'update data of the table: "post"',
          args: [
            {
              name: '_inc',
              description:
                'increments the integer columns with given value of the filtered values',
              type: {
                kind: 'INPUT_OBJECT',
                name: 'post_inc_input',
                ofType: null,
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
            {
              name: '_set',
              description:
                'sets the columns of the filtered rows to the given values',
              type: {
                kind: 'INPUT_OBJECT',
                name: 'post_set_input',
                ofType: null,
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
            {
              name: 'where',
              description: 'filter the rows which have to be updated',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'INPUT_OBJECT',
                  name: 'post_bool_exp',
                  ofType: null,
                  __typename: '__Type',
                },
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
          ],
          type: {
            kind: 'OBJECT',
            name: 'post_mutation_response',
            ofType: null,
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'update_user',
          description: 'update data of the table: "user"',
          args: [
            {
              name: '_inc',
              description:
                'increments the integer columns with given value of the filtered values',
              type: {
                kind: 'INPUT_OBJECT',
                name: 'user_inc_input',
                ofType: null,
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
            {
              name: '_set',
              description:
                'sets the columns of the filtered rows to the given values',
              type: {
                kind: 'INPUT_OBJECT',
                name: 'user_set_input',
                ofType: null,
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
            {
              name: 'where',
              description: 'filter the rows which have to be updated',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'INPUT_OBJECT',
                  name: 'user_bool_exp',
                  ofType: null,
                  __typename: '__Type',
                },
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
          ],
          type: {
            kind: 'OBJECT',
            name: 'user_mutation_response',
            ofType: null,
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
      ],
      inputFields: null,
      interfaces: [],
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'OBJECT',
      name: 'post',
      description: 'columns and relationships of "post"',
      fields: [
        {
          name: 'author_id',
          description: null,
          args: [],
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'SCALAR',
              name: 'Int',
              ofType: null,
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'id',
          description: null,
          args: [],
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'SCALAR',
              name: 'Int',
              ofType: null,
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'title',
          description: null,
          args: [],
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'SCALAR',
              name: 'String',
              ofType: null,
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'userByauthorId',
          description: 'An object relationship',
          args: [],
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'OBJECT',
              name: 'user',
              ofType: null,
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
      ],
      inputFields: null,
      interfaces: [],
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'INPUT_OBJECT',
      name: 'post_arr_rel_insert_input',
      description:
        'input type for inserting array relation for remote table "post"',
      fields: null,
      inputFields: [
        {
          name: 'data',
          description: null,
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'LIST',
              name: null,
              ofType: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'INPUT_OBJECT',
                  name: 'post_insert_input',
                  ofType: null,
                  __typename: '__Type',
                },
                __typename: '__Type',
              },
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: 'on_conflict',
          description: null,
          type: {
            kind: 'INPUT_OBJECT',
            name: 'post_on_conflict',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
      ],
      interfaces: null,
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'INPUT_OBJECT',
      name: 'post_bool_exp',
      description:
        'Boolean expression to filter rows from the table "post". All fields are combined with a logical \'AND\'.',
      fields: null,
      inputFields: [
        {
          name: '_and',
          description: null,
          type: {
            kind: 'LIST',
            name: null,
            ofType: {
              kind: 'INPUT_OBJECT',
              name: 'post_bool_exp',
              ofType: null,
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: '_not',
          description: null,
          type: {
            kind: 'INPUT_OBJECT',
            name: 'post_bool_exp',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: '_or',
          description: null,
          type: {
            kind: 'LIST',
            name: null,
            ofType: {
              kind: 'INPUT_OBJECT',
              name: 'post_bool_exp',
              ofType: null,
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: 'author_id',
          description: null,
          type: {
            kind: 'INPUT_OBJECT',
            name: 'integer_comparison_exp',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: 'id',
          description: null,
          type: {
            kind: 'INPUT_OBJECT',
            name: 'integer_comparison_exp',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: 'title',
          description: null,
          type: {
            kind: 'INPUT_OBJECT',
            name: 'text_comparison_exp',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: 'userByauthorId',
          description: null,
          type: {
            kind: 'INPUT_OBJECT',
            name: 'user_bool_exp',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
      ],
      interfaces: null,
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'ENUM',
      name: 'post_column',
      description: 'columns of table "post"',
      fields: null,
      inputFields: null,
      interfaces: null,
      enumValues: [
        {
          name: 'author_id',
          description: 'column name',
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'id',
          description: 'column name',
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'title',
          description: 'column name',
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
      ],
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'ENUM',
      name: 'post_constraint',
      description: 'unique or primary key constraints on table "post"',
      fields: null,
      inputFields: null,
      interfaces: null,
      enumValues: [
        {
          name: 'post_pkey',
          description: 'unique or primary key constraint',
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
      ],
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'INPUT_OBJECT',
      name: 'post_inc_input',
      description:
        'input type for incrementing integer columne in table "post"',
      fields: null,
      inputFields: [
        {
          name: 'author_id',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'Int',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: 'id',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'Int',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
      ],
      interfaces: null,
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'INPUT_OBJECT',
      name: 'post_insert_input',
      description: 'input type for inserting data into table "post"',
      fields: null,
      inputFields: [
        {
          name: 'author_id',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'Int',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: 'id',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'Int',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: 'title',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'String',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: 'userByauthorId',
          description: null,
          type: {
            kind: 'INPUT_OBJECT',
            name: 'user_obj_rel_insert_input',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
      ],
      interfaces: null,
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'OBJECT',
      name: 'post_mutation_response',
      description: 'response of any mutation on the table "post"',
      fields: [
        {
          name: 'affected_rows',
          description: 'number of affected rows by the mutation',
          args: [],
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'SCALAR',
              name: 'Int',
              ofType: null,
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'returning',
          description: 'data of the affected rows by the mutation',
          args: [],
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'LIST',
              name: null,
              ofType: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'OBJECT',
                  name: 'post',
                  ofType: null,
                  __typename: '__Type',
                },
                __typename: '__Type',
              },
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
      ],
      inputFields: null,
      interfaces: [],
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'INPUT_OBJECT',
      name: 'post_obj_rel_insert_input',
      description:
        'input type for inserting object relation for remote table "post"',
      fields: null,
      inputFields: [
        {
          name: 'data',
          description: null,
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'INPUT_OBJECT',
              name: 'post_insert_input',
              ofType: null,
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: 'on_conflict',
          description: null,
          type: {
            kind: 'INPUT_OBJECT',
            name: 'post_on_conflict',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
      ],
      interfaces: null,
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'INPUT_OBJECT',
      name: 'post_on_conflict',
      description: 'on conflict condition type for table "post"',
      fields: null,
      inputFields: [
        {
          name: 'action',
          description: 'action when conflict occurs (deprecated)',
          type: {
            kind: 'ENUM',
            name: 'conflict_action',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: 'constraint',
          description: null,
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'ENUM',
              name: 'post_constraint',
              ofType: null,
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: 'update_columns',
          description: null,
          type: {
            kind: 'LIST',
            name: null,
            ofType: {
              kind: 'NON_NULL',
              name: null,
              ofType: {
                kind: 'ENUM',
                name: 'post_column',
                ofType: null,
                __typename: '__Type',
              },
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
      ],
      interfaces: null,
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'ENUM',
      name: 'post_order_by',
      description: 'ordering options when selecting data from "post"',
      fields: null,
      inputFields: null,
      interfaces: null,
      enumValues: [
        {
          name: 'author_id_asc',
          description: 'in the ascending order of "author_id", nulls last',
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'author_id_asc_nulls_first',
          description: 'in the ascending order of "author_id", nulls first',
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'author_id_desc',
          description: 'in the descending order of "author_id", nulls last',
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'author_id_desc_nulls_first',
          description: 'in the descending order of "author_id", nulls first',
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'id_asc',
          description: 'in the ascending order of "id", nulls last',
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'id_asc_nulls_first',
          description: 'in the ascending order of "id", nulls first',
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'id_desc',
          description: 'in the descending order of "id", nulls last',
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'id_desc_nulls_first',
          description: 'in the descending order of "id", nulls first',
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'title_asc',
          description: 'in the ascending order of "title", nulls last',
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'title_asc_nulls_first',
          description: 'in the ascending order of "title", nulls first',
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'title_desc',
          description: 'in the descending order of "title", nulls last',
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'title_desc_nulls_first',
          description: 'in the descending order of "title", nulls first',
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
      ],
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'INPUT_OBJECT',
      name: 'post_set_input',
      description: 'input type for updating data in table "post"',
      fields: null,
      inputFields: [
        {
          name: 'author_id',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'Int',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: 'id',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'Int',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: 'title',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'String',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
      ],
      interfaces: null,
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'OBJECT',
      name: 'query_root',
      description: 'query root',
      fields: [
        {
          name: 'post',
          description: 'fetch data from the table: "post"',
          args: [
            {
              name: 'limit',
              description: 'limit the nuber of rows returned',
              type: {
                kind: 'SCALAR',
                name: 'Int',
                ofType: null,
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
            {
              name: 'offset',
              description: 'skip the first n rows. Use only with order_by',
              type: {
                kind: 'SCALAR',
                name: 'Int',
                ofType: null,
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
            {
              name: 'order_by',
              description: 'sort the rows by one or more columns',
              type: {
                kind: 'LIST',
                name: null,
                ofType: {
                  kind: 'NON_NULL',
                  name: null,
                  ofType: {
                    kind: 'ENUM',
                    name: 'post_order_by',
                    ofType: null,
                    __typename: '__Type',
                  },
                  __typename: '__Type',
                },
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
            {
              name: 'where',
              description: 'filter the rows returned',
              type: {
                kind: 'INPUT_OBJECT',
                name: 'post_bool_exp',
                ofType: null,
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
          ],
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'LIST',
              name: null,
              ofType: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'OBJECT',
                  name: 'post',
                  ofType: null,
                  __typename: '__Type',
                },
                __typename: '__Type',
              },
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'post_by_pk',
          description:
            'fetch data from the table: "post" using primary key columns',
          args: [
            {
              name: 'id',
              description: null,
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'SCALAR',
                  name: 'Int',
                  ofType: null,
                  __typename: '__Type',
                },
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
          ],
          type: {
            kind: 'OBJECT',
            name: 'post',
            ofType: null,
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'user',
          description: 'fetch data from the table: "user"',
          args: [
            {
              name: 'limit',
              description: 'limit the nuber of rows returned',
              type: {
                kind: 'SCALAR',
                name: 'Int',
                ofType: null,
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
            {
              name: 'offset',
              description: 'skip the first n rows. Use only with order_by',
              type: {
                kind: 'SCALAR',
                name: 'Int',
                ofType: null,
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
            {
              name: 'order_by',
              description: 'sort the rows by one or more columns',
              type: {
                kind: 'LIST',
                name: null,
                ofType: {
                  kind: 'NON_NULL',
                  name: null,
                  ofType: {
                    kind: 'ENUM',
                    name: 'user_order_by',
                    ofType: null,
                    __typename: '__Type',
                  },
                  __typename: '__Type',
                },
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
            {
              name: 'where',
              description: 'filter the rows returned',
              type: {
                kind: 'INPUT_OBJECT',
                name: 'user_bool_exp',
                ofType: null,
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
          ],
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'LIST',
              name: null,
              ofType: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'OBJECT',
                  name: 'user',
                  ofType: null,
                  __typename: '__Type',
                },
                __typename: '__Type',
              },
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'user_by_pk',
          description:
            'fetch data from the table: "user" using primary key columns',
          args: [
            {
              name: 'id',
              description: null,
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'SCALAR',
                  name: 'Int',
                  ofType: null,
                  __typename: '__Type',
                },
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
          ],
          type: {
            kind: 'OBJECT',
            name: 'user',
            ofType: null,
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
      ],
      inputFields: null,
      interfaces: [],
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'OBJECT',
      name: 'subscription_root',
      description: 'subscription root',
      fields: [
        {
          name: 'post',
          description: 'fetch data from the table: "post"',
          args: [
            {
              name: 'limit',
              description: 'limit the nuber of rows returned',
              type: {
                kind: 'SCALAR',
                name: 'Int',
                ofType: null,
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
            {
              name: 'offset',
              description: 'skip the first n rows. Use only with order_by',
              type: {
                kind: 'SCALAR',
                name: 'Int',
                ofType: null,
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
            {
              name: 'order_by',
              description: 'sort the rows by one or more columns',
              type: {
                kind: 'LIST',
                name: null,
                ofType: {
                  kind: 'NON_NULL',
                  name: null,
                  ofType: {
                    kind: 'ENUM',
                    name: 'post_order_by',
                    ofType: null,
                    __typename: '__Type',
                  },
                  __typename: '__Type',
                },
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
            {
              name: 'where',
              description: 'filter the rows returned',
              type: {
                kind: 'INPUT_OBJECT',
                name: 'post_bool_exp',
                ofType: null,
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
          ],
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'LIST',
              name: null,
              ofType: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'OBJECT',
                  name: 'post',
                  ofType: null,
                  __typename: '__Type',
                },
                __typename: '__Type',
              },
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'post_by_pk',
          description:
            'fetch data from the table: "post" using primary key columns',
          args: [
            {
              name: 'id',
              description: null,
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'SCALAR',
                  name: 'Int',
                  ofType: null,
                  __typename: '__Type',
                },
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
          ],
          type: {
            kind: 'OBJECT',
            name: 'post',
            ofType: null,
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'user',
          description: 'fetch data from the table: "user"',
          args: [
            {
              name: 'limit',
              description: 'limit the nuber of rows returned',
              type: {
                kind: 'SCALAR',
                name: 'Int',
                ofType: null,
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
            {
              name: 'offset',
              description: 'skip the first n rows. Use only with order_by',
              type: {
                kind: 'SCALAR',
                name: 'Int',
                ofType: null,
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
            {
              name: 'order_by',
              description: 'sort the rows by one or more columns',
              type: {
                kind: 'LIST',
                name: null,
                ofType: {
                  kind: 'NON_NULL',
                  name: null,
                  ofType: {
                    kind: 'ENUM',
                    name: 'user_order_by',
                    ofType: null,
                    __typename: '__Type',
                  },
                  __typename: '__Type',
                },
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
            {
              name: 'where',
              description: 'filter the rows returned',
              type: {
                kind: 'INPUT_OBJECT',
                name: 'user_bool_exp',
                ofType: null,
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
          ],
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'LIST',
              name: null,
              ofType: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'OBJECT',
                  name: 'user',
                  ofType: null,
                  __typename: '__Type',
                },
                __typename: '__Type',
              },
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'user_by_pk',
          description:
            'fetch data from the table: "user" using primary key columns',
          args: [
            {
              name: 'id',
              description: null,
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'SCALAR',
                  name: 'Int',
                  ofType: null,
                  __typename: '__Type',
                },
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
          ],
          type: {
            kind: 'OBJECT',
            name: 'user',
            ofType: null,
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
      ],
      inputFields: null,
      interfaces: [],
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'INPUT_OBJECT',
      name: 'text_comparison_exp',
      description:
        "expression to compare columns of type text. All fields are combined with logical 'AND'.",
      fields: null,
      inputFields: [
        {
          name: '_eq',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'String',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: '_gt',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'String',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: '_gte',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'String',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: '_ilike',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'String',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: '_in',
          description: null,
          type: {
            kind: 'LIST',
            name: null,
            ofType: {
              kind: 'SCALAR',
              name: 'String',
              ofType: null,
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: '_is_null',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'Boolean',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: '_like',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'String',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: '_lt',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'String',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: '_lte',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'String',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: '_neq',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'String',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: '_nilike',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'String',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: '_nin',
          description: null,
          type: {
            kind: 'LIST',
            name: null,
            ofType: {
              kind: 'SCALAR',
              name: 'String',
              ofType: null,
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: '_nlike',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'String',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: '_nsimilar',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'String',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: '_similar',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'String',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
      ],
      interfaces: null,
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'OBJECT',
      name: 'user',
      description: 'columns and relationships of "user"',
      fields: [
        {
          name: 'id',
          description: null,
          args: [],
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'SCALAR',
              name: 'Int',
              ofType: null,
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'name',
          description: null,
          args: [],
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'SCALAR',
              name: 'String',
              ofType: null,
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'postsByauthorId',
          description: 'An array relationship',
          args: [
            {
              name: 'limit',
              description: 'limit the nuber of rows returned',
              type: {
                kind: 'SCALAR',
                name: 'Int',
                ofType: null,
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
            {
              name: 'offset',
              description: 'skip the first n rows. Use only with order_by',
              type: {
                kind: 'SCALAR',
                name: 'Int',
                ofType: null,
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
            {
              name: 'order_by',
              description: 'sort the rows by one or more columns',
              type: {
                kind: 'LIST',
                name: null,
                ofType: {
                  kind: 'NON_NULL',
                  name: null,
                  ofType: {
                    kind: 'ENUM',
                    name: 'post_order_by',
                    ofType: null,
                    __typename: '__Type',
                  },
                  __typename: '__Type',
                },
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
            {
              name: 'where',
              description: 'filter the rows returned',
              type: {
                kind: 'INPUT_OBJECT',
                name: 'post_bool_exp',
                ofType: null,
                __typename: '__Type',
              },
              defaultValue: null,
              __typename: '__InputValue',
            },
          ],
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'LIST',
              name: null,
              ofType: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'OBJECT',
                  name: 'post',
                  ofType: null,
                  __typename: '__Type',
                },
                __typename: '__Type',
              },
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
      ],
      inputFields: null,
      interfaces: [],
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'INPUT_OBJECT',
      name: 'user_arr_rel_insert_input',
      description:
        'input type for inserting array relation for remote table "user"',
      fields: null,
      inputFields: [
        {
          name: 'data',
          description: null,
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'LIST',
              name: null,
              ofType: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'INPUT_OBJECT',
                  name: 'user_insert_input',
                  ofType: null,
                  __typename: '__Type',
                },
                __typename: '__Type',
              },
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: 'on_conflict',
          description: null,
          type: {
            kind: 'INPUT_OBJECT',
            name: 'user_on_conflict',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
      ],
      interfaces: null,
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'INPUT_OBJECT',
      name: 'user_bool_exp',
      description:
        'Boolean expression to filter rows from the table "user". All fields are combined with a logical \'AND\'.',
      fields: null,
      inputFields: [
        {
          name: '_and',
          description: null,
          type: {
            kind: 'LIST',
            name: null,
            ofType: {
              kind: 'INPUT_OBJECT',
              name: 'user_bool_exp',
              ofType: null,
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: '_not',
          description: null,
          type: {
            kind: 'INPUT_OBJECT',
            name: 'user_bool_exp',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: '_or',
          description: null,
          type: {
            kind: 'LIST',
            name: null,
            ofType: {
              kind: 'INPUT_OBJECT',
              name: 'user_bool_exp',
              ofType: null,
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: 'id',
          description: null,
          type: {
            kind: 'INPUT_OBJECT',
            name: 'integer_comparison_exp',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: 'name',
          description: null,
          type: {
            kind: 'INPUT_OBJECT',
            name: 'text_comparison_exp',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: 'postsByauthorId',
          description: null,
          type: {
            kind: 'INPUT_OBJECT',
            name: 'post_bool_exp',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
      ],
      interfaces: null,
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'ENUM',
      name: 'user_column',
      description: 'columns of table "user"',
      fields: null,
      inputFields: null,
      interfaces: null,
      enumValues: [
        {
          name: 'id',
          description: 'column name',
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'name',
          description: 'column name',
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
      ],
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'ENUM',
      name: 'user_constraint',
      description: 'unique or primary key constraints on table "user"',
      fields: null,
      inputFields: null,
      interfaces: null,
      enumValues: [
        {
          name: 'user_pkey',
          description: 'unique or primary key constraint',
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
      ],
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'INPUT_OBJECT',
      name: 'user_inc_input',
      description:
        'input type for incrementing integer columne in table "user"',
      fields: null,
      inputFields: [
        {
          name: 'id',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'Int',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
      ],
      interfaces: null,
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'INPUT_OBJECT',
      name: 'user_insert_input',
      description: 'input type for inserting data into table "user"',
      fields: null,
      inputFields: [
        {
          name: 'id',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'Int',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: 'name',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'String',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: 'postsByauthorId',
          description: null,
          type: {
            kind: 'INPUT_OBJECT',
            name: 'post_arr_rel_insert_input',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
      ],
      interfaces: null,
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'OBJECT',
      name: 'user_mutation_response',
      description: 'response of any mutation on the table "user"',
      fields: [
        {
          name: 'affected_rows',
          description: 'number of affected rows by the mutation',
          args: [],
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'SCALAR',
              name: 'Int',
              ofType: null,
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
        {
          name: 'returning',
          description: 'data of the affected rows by the mutation',
          args: [],
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'LIST',
              name: null,
              ofType: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'OBJECT',
                  name: 'user',
                  ofType: null,
                  __typename: '__Type',
                },
                __typename: '__Type',
              },
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__Field',
        },
      ],
      inputFields: null,
      interfaces: [],
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'INPUT_OBJECT',
      name: 'user_obj_rel_insert_input',
      description:
        'input type for inserting object relation for remote table "user"',
      fields: null,
      inputFields: [
        {
          name: 'data',
          description: null,
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'INPUT_OBJECT',
              name: 'user_insert_input',
              ofType: null,
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: 'on_conflict',
          description: null,
          type: {
            kind: 'INPUT_OBJECT',
            name: 'user_on_conflict',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
      ],
      interfaces: null,
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'INPUT_OBJECT',
      name: 'user_on_conflict',
      description: 'on conflict condition type for table "user"',
      fields: null,
      inputFields: [
        {
          name: 'action',
          description: 'action when conflict occurs (deprecated)',
          type: {
            kind: 'ENUM',
            name: 'conflict_action',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: 'constraint',
          description: null,
          type: {
            kind: 'NON_NULL',
            name: null,
            ofType: {
              kind: 'ENUM',
              name: 'user_constraint',
              ofType: null,
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: 'update_columns',
          description: null,
          type: {
            kind: 'LIST',
            name: null,
            ofType: {
              kind: 'NON_NULL',
              name: null,
              ofType: {
                kind: 'ENUM',
                name: 'user_column',
                ofType: null,
                __typename: '__Type',
              },
              __typename: '__Type',
            },
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
      ],
      interfaces: null,
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'ENUM',
      name: 'user_order_by',
      description: 'ordering options when selecting data from "user"',
      fields: null,
      inputFields: null,
      interfaces: null,
      enumValues: [
        {
          name: 'id_asc',
          description: 'in the ascending order of "id", nulls last',
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'id_asc_nulls_first',
          description: 'in the ascending order of "id", nulls first',
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'id_desc',
          description: 'in the descending order of "id", nulls last',
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'id_desc_nulls_first',
          description: 'in the descending order of "id", nulls first',
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'name_asc',
          description: 'in the ascending order of "name", nulls last',
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'name_asc_nulls_first',
          description: 'in the ascending order of "name", nulls first',
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'name_desc',
          description: 'in the descending order of "name", nulls last',
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
        {
          name: 'name_desc_nulls_first',
          description: 'in the descending order of "name", nulls first',
          isDeprecated: false,
          deprecationReason: null,
          __typename: '__EnumValue',
        },
      ],
      possibleTypes: null,
      __typename: '__Type',
    },
    {
      kind: 'INPUT_OBJECT',
      name: 'user_set_input',
      description: 'input type for updating data in table "user"',
      fields: null,
      inputFields: [
        {
          name: 'id',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'Int',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
        {
          name: 'name',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'String',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
      ],
      interfaces: null,
      enumValues: null,
      possibleTypes: null,
      __typename: '__Type',
    },
  ],
  directives: [
    {
      name: 'include',
      description: null,
      locations: ['FIELD', 'FRAGMENT_SPREAD', 'INLINE_FRAGMENT'],
      args: [
        {
          name: 'if',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'Boolean',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
      ],
    },
    {
      name: 'skip',
      description: null,
      locations: ['FIELD', 'FRAGMENT_SPREAD', 'INLINE_FRAGMENT'],
      args: [
        {
          name: 'if',
          description: null,
          type: {
            kind: 'SCALAR',
            name: 'Boolean',
            ofType: null,
            __typename: '__Type',
          },
          defaultValue: null,
          __typename: '__InputValue',
        },
      ],
    },
  ],
};
